### ISSUE TITLE
invalid htpasswords file - user local@wandb.com was already defined

### ISSUE THREAD

**Issue by narayanacharya6** [wandb/local#12]
Hi, I am just trying out the local instance for getting started. I followed the steps as mentioned on the readme to start a local instance. 

Steps:
```
$ pip install wandb --upgrade
...

$ wandb --version
wandb, version 0.10.22

$ wandb local
...
Status: Downloaded newer image for wandb/local:latest
wandb: W&B local started at http://localhost:8080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
wandb: You can find your API key in your browser here: http://localhost:8080/authorize
wandb: Paste an API key from your profile and hit enter:
```

I get the below stack trace when I try to access `http://localhost:8080/authorize` in the browser.

```
An error was encountered while starting the container:
2021/03/17 16:26:37 Error unsetting password for restore mode user invalid htpasswords file - user local@wandb.com was already defined
panic: invalid htpasswords file - user local@wandb.com was already defined

goroutine 1 [running]:
main.ensureDefaults(0x122c3dd, 0x4, 0x0, 0x0, 0xc00048cde0, 0x16, 0xc00033b1e0, 0xa, 0x12432d5, 0x1a, ...)
	/home/runner/work/core/core/src/github.com/wandb/core/services/local/cmd/local/main.go:611 +0x5b2
main.commands(0x122c3dd, 0x4, 0x0, 0x0, 0xc00048cde0, 0x16, 0xc00033b1e0, 0xa, 0x12432d5, 0x1a, ...)
	/home/runner/work/core/core/src/github.com/wandb/core/services/local/cmd/local/main.go:407 +0x121e
main.main()
	/home/runner/work/core/core/src/github.com/wandb/core/services/local/cmd/local/main.go:675 +0x105
If this error persists, please contact support@wandb.com and include the message above.
```

Any pointers as to what I might be doing wrong here?

**Comment by vanpelt** [comment]
@narayanacharya6 haven't seen this one before.  You can likely fix it by shelling into the container and moving the existing htpasswd file:

```
docker exec -it wandb-local bash
mv /vol/env/users.htpasswd /vol/env/users.htpasswd.old
exit
docker stop wandb-local
wandb local
```

**Comment by narayanacharya6** [comment]
That worked! Thanks @vanpelt
