### ISSUE TITLE
Loading is taking longer than expected.

### ISSUE THREAD

**Issue by windxrz** [wandb/local#7]
### Describe the bug
When I run `wandb local`, the terminal requires an API key as follows.
![Screen Shot 2021-01-11 at 12 14 28](https://user-images.githubusercontent.com/18761561/104146739-b188c680-5406-11eb-8938-894d42fe7983.png)
But when I open the link in the browser, it shows that "Loading is taking longer than expected."
![Screen Shot 2021-01-11 at 12 16 16](https://user-images.githubusercontent.com/18761561/104146776-da10c080-5406-11eb-98bf-341e8a379524.png)
I run `wandb local --no-daemon` and it shows
![Screen Shot 2021-01-12 at 17 03 18](https://user-images.githubusercontent.com/18761561/104292727-28ea5300-54f8-11eb-8d59-01896beff9e0.png)

### Operating system
- Ubuntu 18.04
- Python 3.7.9
- Wandb 0.10.13

**Comment by Bovey0809** [comment]
I'm facing the same issue , it takes a long time and never log in .

**Comment by vanpelt** [comment]
@windxrz this indicates mysql couldn't start likely due to file permissions or docker file driver issues.  Can you try starting it with `wandb local --upgrade` and share the input.  Also the output of `docker volume inspect wandb` would be helpful.

@Bovey0809 can you share the output of `wandb local --no-daemon`?

**Comment by windxrz** [comment]
@vanpelt Thanks for the response. I upgrade Wandb to the latest version by `wandb local --upgrade` but the results are the same.
```
Using default tag: latest
latest: Pulling from wandb/local
Digest: sha256:9439e2d38d72858d43aff525a16135c9e68bd4b241339c626fd79c0adda486ec
Status: Image is up to date for wandb/local:latest
docker.io/wandb/local:latest
wandb-local
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Running /etc/my_init.d/02_load-settings.sh...
*** Booting runit daemon...
*** Runit started as PID 47
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
main.main()
        /home/runner/work/core/core/src/github.com/wandb/core/services/gorilla/cmd/migrate/main.go:57 +0xb65
panic: dial tcp 127.0.0.1:3306: connect: connection refused
```
In addition, the output of `docker volume inspect wandb` is as follows
```
[
    {
        "CreatedAt": "2021-01-10T22:51:20+08:00",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/wandb/_data",
        "Name": "wandb",
        "Options": null,
        "Scope": "local"
    }
]
```

**Comment by vanpelt** [comment]
Great thanks, let's look at the mysql logs.  Can you run the following after you've started a local container? `docker exec -it wandb-local cat /var/log/mysql.log`

**Comment by windxrz** [comment]
```
./run: line 35: fg: job has terminated
mysqld: Can't create directory '/vol/mysql/' (Errcode: 17 - File exists)
2021-01-16T03:20:00.586161Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2021-01-16T03:20:00.588385Z 0 [ERROR] Aborting

2021-01-16T03:20:00.804432Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2021-01-16T03:20:00.804592Z 0 [Warning] Can't create test file /vol/mysql/2b5d2a25275e.lower-test
2021-01-16T03:20:00.804637Z 0 [Note] mysqld (mysqld 5.7.32-0ubuntu0.18.04.1) starting as process 414 ...
2021-01-16T03:20:00.808654Z 0 [Warning] Can't create test file /vol/mysql/2b5d2a25275e.lower-test
2021-01-16T03:20:00.808681Z 0 [Warning] Can't create test file /vol/mysql/2b5d2a25275e.lower-test
2021-01-16T03:20:00.809129Z 0 [Warning] One can only use the --user switch if running as root

2021-01-16T03:20:00.812087Z 0 [Note] InnoDB: PUNCH HOLE support available
2021-01-16T03:20:00.812107Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2021-01-16T03:20:00.812112Z 0 [Note] InnoDB: Uses event mutexes
2021-01-16T03:20:00.812117Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2021-01-16T03:20:00.812121Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-01-16T03:20:00.812126Z 0 [Note] InnoDB: Using Linux native AIO
2021-01-16T03:20:00.812618Z 0 [Note] InnoDB: Number of pools: 1
2021-01-16T03:20:00.812753Z 0 [Note] InnoDB: Using CPU crc32 instructions
2021-01-16T03:20:00.815120Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2021-01-16T03:20:00.827704Z 0 [Note] InnoDB: Completed initialization of buffer pool
2021-01-16T03:20:00.830570Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2021-01-16T03:20:00.840574Z 0 [Note] InnoDB: The first innodb_system data file 'ibdata1' did not exist. A new tablespace will be created!
2021-01-16T03:20:00.840865Z 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.
2021-01-16T03:20:00.840883Z 0 [ERROR] InnoDB: The error means mysqld does not have the access rights to the directory.
2021-01-16T03:20:00.840889Z 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.
2021-01-16T03:20:00.840894Z 0 [ERROR] InnoDB: The error means mysqld does not have the access rights to the directory.
2021-01-16T03:20:00.840899Z 0 [ERROR] InnoDB: Cannot open datafile './ibdata1'
2021-01-16T03:20:00.840913Z 0 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!
2021-01-16T03:20:00.840919Z 0 [ERROR] InnoDB: InnoDB Database creation was aborted with error Cannot open a file. You may need to delete the ibdata1 file before trying to start up again.
2021-01-16T03:20:01.443211Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
2021-01-16T03:20:01.443257Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2021-01-16T03:20:01.443267Z 0 [ERROR] Failed to initialize builtin plugins.
2021-01-16T03:20:01.443275Z 0 [ERROR] Aborting

2021-01-16T03:20:01.443296Z 0 [Note] Binlog end
2021-01-16T03:20:01.443367Z 0 [Note] Shutting down plugin 'CSV'
2021-01-16T03:20:01.445713Z 0 [Note] mysqld: Shutdown complete
```

**Comment by vanpelt** [comment]
Hey windxrz the errors indicates the container can't write to the filesystem that you're mounting in.  This looks like a permissions issue, you may need to run the command as `sudo` or change the file permissions of the mount.  You can run `docker volume inspect wandb` to see where the underlying volume is on your OS.

**Comment by vanpelt** [comment]
The nuclear option is to start from scratch by removing the old volume so a new one is created.  This will loss all data mounted into that volume so use with caution: `wandb volume rm wandb`

**Comment by windxrz** [comment]
After I update wandb local to the latest version, the issue still exists. The latest output of `wandb local --no-daemon` is
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Running /etc/my_init.d/02_load-settings.sh...
*** Booting runit daemon...
*** Runit started as PID 46
panic: Dirty database version 5. Fix and force version.

goroutine 1 [running]:
main.main()
        /home/runner/work/core/core/src/github.com/wandb/core/services/gorilla/cmd/migrate/main.go:115 +0xb05
```
The output of `docker exec -it wandb-local cat /var/log/mysql.log` is
```
2021-02-23T06:27:11.944311Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see docu$
entation for more details).
2021-02-23T06:27:11.946565Z 0 [Note] mysqld (mysqld 5.7.33-0ubuntu0.18.04.1) starting as process 106 ...
2021-02-23T06:27:11.949371Z 0 [Warning] One can only use the --user switch if running as root

2021-02-23T06:27:11.952468Z 0 [Note] InnoDB: PUNCH HOLE support available
2021-02-23T06:27:11.952491Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2021-02-23T06:27:11.952498Z 0 [Note] InnoDB: Uses event mutexes
2021-02-23T06:27:11.952504Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2021-02-23T06:27:11.952510Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-02-23T06:27:11.952516Z 0 [Note] InnoDB: Using Linux native AIO
2021-02-23T06:27:11.953045Z 0 [Note] InnoDB: Number of pools: 1
2021-02-23T06:27:11.953178Z 0 [Note] InnoDB: Using CPU crc32 instructions
2021-02-23T06:27:11.955653Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2021-02-23T06:27:11.970210Z 0 [Note] InnoDB: Completed initialization of buffer pool
2021-02-23T06:27:11.973206Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setprio$ity().
2021-02-23T06:27:11.985433Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2021-02-23T06:27:12.085225Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-02-23T06:27:12.085279Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-02-23T06:27:12.217513Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-02-23T06:27:12.218894Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2021-02-23T06:27:12.218917Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2021-02-23T06:27:12.219662Z 0 [Note] InnoDB: 5.7.33 started; log sequence number 8575538
2021-02-23T06:27:12.219832Z 0 [Note] InnoDB: Loading buffer pool(s) from /vol/mysql/ib_buffer_pool
2021-02-23T06:27:12.220301Z 0 [Note] Plugin 'FEDERATED' is disabled.
2021-02-23T06:27:12.223548Z 0 [Note] InnoDB: Buffer pool(s) load completed at 210223  6:27:12
2021-02-23T06:27:12.232472Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2021-02-23T06:27:12.232489Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2021-02-23T06:27:12.233129Z 0 [Warning] CA certificate ca.pem is self signed.
2021-02-23T06:27:12.233170Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2021-02-23T06:27:12.233247Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2021-02-23T06:27:12.233275Z 0 [Note] IPv6 is available.
2021-02-23T06:27:12.233283Z 0 [Note]   - '::' resolves to '::';
2021-02-23T06:27:12.233298Z 0 [Note] Server socket created on IP: '::'.
2021-02-23T06:27:12.286003Z 0 [Note] Event Scheduler: Loaded 0 events
2021-02-23T06:27:12.286337Z 0 [Note] mysqld: ready for connections.
Version: '5.7.33-0ubuntu0.18.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)
2021-02-23T06:27:12.791152Z 5 [Note] Aborted connection 5 to db: 'wandb_local' user: 'wandb_local' host: '127.0.0.1' (Got an error reading communication packets)
2021-02-23T06:27:12.791212Z 4 [Note] Aborted connection 4 to db: 'wandb_local' user: 'wandb_local' host: '127.0.0.1' (Got an error reading communication packets)
exec mysqld >> /var/log/mysql.log 2>&1
```

**Operating system**:
- Ubuntu 18.04
- Python 3.7.9
- Wandb 0.10.20
- Wandb local digest 041913476f4710f6f3727f15c4c413bebafbf7cc724ba451046f9eeb125b421e

**Comment by vanpelt** [comment]
Hey @windxrz this indicates that your database failed to migrate likely due to a mis-configured docker volume or killing a previously running wandb/local container.  You can get past this error by deleting the bad volume assuming you don't have any data saved to it with:

```
docker stop wandb-local
docker volume rm wandb
wandb local
```

**Comment by windxrz** [comment]
@vanpelt Thanks! The issue is fixed for me.
