### ISSUE TITLE
Error while downloading settings from external bucket specified in env var BUCKET

### ISSUE THREAD

**Issue by HaoLiuHust** [wandb/local#80]
after my server reboot, wandb-local can not start up with this error msg

**Comment by HaoLiuHust** [comment]
I am not use external s3 for now, I will reopen it if I have to use s3 again

**Comment by wsszh** [comment]
Hi, I have the similar problem.

**Comment by wsszh** [comment]
> Hi, I'm trying to deploy wandb using helm in my own k8s cluster and I have the similar problem. Here's the logs in wandb pod:
> 
> > *** Running /etc/my_init.d/01_enable-services.sh...
> > *** Found custom SSL certifcates, updating root trust...
> > Updating certificates in /etc/ssl/certs...
> > rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
> > 1 added, 0 removed; done.
> > Running hooks in /etc/ca-certificates/update.d...
> > done.
> > *** Enabling production mode
> > *** Running /etc/my_init.d/02_load-settings.sh...
> > *** Loading settings...
> > !!! Error while downloading settings from external bucket specified in env var BUCKET
> > panic: NoSuchBucket:
> > status code: 404, request id: tx00000000000000cee1376-0065eea589-a20e921-default, host id:
> > goroutine 1 [running]:
> > main.commands({{0x16786d3, 0x4}, {0xc00004a007, 0x6f}, {0xc000044046, 0x16}, {0xc0000462d2, 0xa}, {0x1695802, 0x1a}, ...})
> > /home/circleci/go/src/github.com/wandb/core/services/local/cmd/local/main.go:386 +0x2988
> > main.main()
> > /home/circleci/go/src/github.com/wandb/core/services/local/cmd/local/main.go:740 +0x78
> > !!! Failed to load settings. If this issue persists, please contact [support@wandb.com](mailto:support@wandb.com).
> > *** Booting runit daemon...
> > *** Runit started as PID 1045

I've solved it. I just set the wrong s3 bucket name in helm before...
