### ISSUE TITLE
panic: dial tcp 127.0.0.1:3306 and 

### ISSUE THREAD

**Issue by chongaxiaopenzai** [wandb/local#97]
In my 8080:/home,i have the question.

Loading your local environment...
Loading is taking longer than expected. Check stdout, or the system logs at /var/log for error messages. You can restart your server with the environment variable LOCAL_RESTORE=true to regain access if you're unable to login.

**Comment by chongaxiaopenzai** [comment]
when i run docker logs wandb-local

Bucket created successfully `local/local-files`.
Successfully added arn:minio:sqs:wandb-local:_:redis
*** Migrating database...
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/wandb/core/services/gorilla/cmd.(*migrateCommander).MainCmd(0xc000efa950, {0xc000f3a220, 0x2, 0x2})
	/mnt/ramdisk/core/services/gorilla/cmd/migrate.go:88 +0x9b4
main.main()
	/mnt/ramdisk/core/services/gorilla/cmd/megabinary/main.go:57 +0x227
*** Setting up mysql database...
*** Migrating database...
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/wandb/core/services/gorilla/cmd.(*migrateCommander).MainCmd(0xc0004ea1a0, {0xc0000b6220, 0x2, 0x2})
	/mnt/ramdisk/core/services/gorilla/cmd/migrate.go:88 +0x9b4
main.main()
	/mnt/ramdisk/core/services/gorilla/cmd/megabinary/main.go:57 +0x227
*** Setting up mysql database...
*** Migrating database...
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/wandb/core/services/gorilla/cmd.(*migrateCommander).MainCmd(0xc000cfaa00, {0xc000d322a0, 0x2, 0x2})
	/mnt/ramdisk/core/services/gorilla/cmd/migrate.go:88 +0x9b4
main.main()
	/mnt/ramdisk/core/services/gorilla/cmd/megabinary/main.go:57 +0x227
*** Setting up mysql database...
*** Migrating database...
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/wandb/core/services/gorilla/cmd.(*migrateCommander).MainCmd(0xc000d12a10, {0xc000d2a2a0, 0x2, 0x2})
	/mnt/ramdisk/core/services/gorilla/cmd/migrate.go:88 +0x9b4
main.main()
	/mnt/ramdisk/core/services/gorilla/cmd/megabinary/main.go:57 +0x227
*** Setting up mysql database...
*** Migrating database...
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/wandb/core/services/gorilla/cmd.(*migrateCommander).MainCmd(0xc000e169e0, {0xc000e107c0, 0x2, 0x2})
	/mnt/ramdisk/core/services/gorilla/cmd/migrate.go:88 +0x9b4
main.main()
	/mnt/ramdisk/core/services/gorilla/cmd/megabinary/main.go:57 +0x227
*** Setting up mysql database...
*** Migrating database...
panic: dial tcp 127.0.0.1:3306: connect: connection refused

**Comment by chongaxiaopenzai** [comment]
so i run the docker exec -it wandb-local cat /var/log/mysql.log
it tell me mysql has died.
information that should help you find out what is causing the crash.
2022-11-11T13:18:18.427852Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2022-11-11T13:18:18.431415Z 0 [Note] mysqld (mysqld 5.7.40) starting as process 2658 ...
2022-11-11T13:18:18.433868Z 0 [ERROR] Failed to create timer notify thread (errno= 1).
2022-11-11T13:18:18.433885Z 0 [ERROR] Failed to initialize timer component (errno 1).
2022-11-11T13:18:18.436648Z 0 [Note] InnoDB: PUNCH HOLE support available
2022-11-11T13:18:18.436684Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-11-11T13:18:18.436692Z 0 [Note] InnoDB: Uses event mutexes
2022-11-11T13:18:18.436699Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2022-11-11T13:18:18.436705Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
2022-11-11T13:18:18.436712Z 0 [Note] InnoDB: Using Linux native AIO
2022-11-11T13:18:18.437377Z 0 [Note] InnoDB: Number of pools: 1
2022-11-11T13:18:18.437548Z 0 [Note] InnoDB: Using CPU crc32 instructions
2022-11-11T13:18:18.440186Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-11-11T13:18:18.453278Z 0 [Note] InnoDB: Completed initialization of buffer pool
2022-11-11T13:18:18.457008Z 0 [ERROR] [FATAL] InnoDB: pthread_create returned 1
2022-11-11 13:18:18 0x7f2c35656740  InnoDB: Assertion failure in thread 139827851126592 in file ut0ut.cc line 921
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.7/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
13:18:18 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
Attempting to collect some information that could help diagnose the problem.
As this is a crash and something is definitely wrong, the information
collection process might fail.

key_buffer_size=8388608
read_buffer_size=131072
max_used_connections=0
max_threads=500
thread_count=0
connection_count=0
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 206887 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0 thread_stack 0x40000
mysqld(my_print_stacktrace+0x3b)[0x55dbfcee071b]
mysqld(handle_fatal_signal+0x377)[0x55dbfc76b907]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f2c3569d520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f2c356f1a7c]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f2c3569d476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f2c356837f3]
mysqld(+0x6b0adc)[0x55dbfc741adc]
mysqld(_ZN2ib5fatalD1Ev+0x66)[0x55dbfd28f406]
mysqld(_Z21os_thread_create_funcPFPvS_ES_Pm+0x257)[0x55dbfd17dc57]
mysqld(_Z34innobase_start_or_create_for_mysqlv+0x1c7a)[0x55dbfd236b4a]
mysqld(+0x106e9ad)[0x55dbfd0ff9ad]
mysqld(_Z24ha_initialize_handlertonP13st_plugin_int+0x4f)[0x55dbfc7c05af]
mysqld(+0xc20ee5)[0x55dbfccb1ee5]
mysqld(_Z40plugin_register_builtin_and_init_core_sePiPPc+0x1e5)[0x55dbfccb5405]
mysqld(+0x6d4960)[0x55dbfc765960]
mysqld(_Z11mysqld_mainiPPc+0x79e)[0x55dbfc76702e]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f2c35684d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f2c35684e40]
mysqld(_start+0x2a)[0x55dbfc75b5ea]
The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.

**Comment by chongaxiaopenzai** [comment]
ok, when i use the https://docs.wandb.ai/guides/self-hosted/setup/on-premise-baremetal#mysql-database
it show:
!! Invalid MySQL database settings -- the instance cannot start. Please change the settings with envrionment variables, or start the container with the LOCAL_RESTORE environment variable set to "true".
!!! Errors are:
!!! - dial tcp 127.0.0.1:3306: connect: connection refused
!!! Failed to load settings. If this issue persists, please contact support@wandb.com.
*** Booting runit daemon...
*** Runit started as PID 46

**Comment by chongaxiaopenzai** [comment]
Well, I've solved the problem.
I tried to use wandb local on my Windows computer, and it worked successfully.
So I guess it's the Docker version.
So I uninstalled Docker on my Ubuntu computer
Downloaded the latest version of Docker.
